# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('path_banner', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
