# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lesson.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=lesson.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=lesson.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=lesson.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=lesson.models.upload_location)),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Task description')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('timePost', models.TimeField(null=True, verbose_name='Time FORMAT HH:MM:SS')),
                ('title_paragraf_1', models.CharField(max_length=30, null=True)),
                ('description_paragraf_1', models.CharField(max_length=5000, null=True)),
                ('title_paragraf_2', models.CharField(max_length=30, null=True)),
                ('description_paragraf_2', models.CharField(max_length=5000, null=True)),
                ('title_paragraf_3', models.CharField(max_length=30, null=True)),
                ('description_paragraf_3', models.CharField(max_length=5000, null=True)),
                ('title_paragraf_4', models.CharField(max_length=30, null=True)),
                ('description_paragraf_4', models.CharField(max_length=5000, null=True)),
                ('title_paragraf_5', models.CharField(max_length=30, null=True)),
                ('description_paragraf_5', models.CharField(max_length=5000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.Domain')),
            ],
            options={
                'get_latest_by': 'creation_date',
            },
        ),
    ]
